### ISSUE TITLE
citybuilder [epics] - v1 basic, v2 ar setup, v3 categories & controls

### ISSUE THREAD

**Issue by kfarr** [3DStreet/citybuilderjr#18]
business goal:
- create a small "polished" webxr app for q3 + avp with hands control as primary input
- show example of workflow from gltf to glb to app
- provide a simpler alternative compared to 3dstreet for playing with urban planning concepts
- bring spirit of legacy a-frame city builder into mixed reality
- provide a companion app for coloring book back page 

v1 - basic - tiles only
- [x] - AG same object in cell as selected, rotate upon click https://github.com/3DStreet/citybuilderjr/issues/16
- [x] - AG replace (don't add to grid stack) https://github.com/3DStreet/citybuilderjr/issues/15
- [ ] - KF - remove duplicate buildings without bases
- [ ] - bug fix double press https://github.com/3DStreet/citybuilderjr/issues/23
- [ ] - KF hands controls - as a user i should be able to use this in hmd without a controller (on q3 or avp). I point my left hand and it creates a ray (like laser controls) and with my right hand I use my index and thumb to "select" and indicate placing an item in the grid cursor location (or rotating, etc) 
- [ ] - KF show only ground-tiles that should snap (based on category or [bounding box -1, -1 to 1, 1 such as](https://github.com/3DStreet/citybuilderjr/blob/main/catalog.json#L229C1-L238C7)) -- filter out "free place" props for now like vehicles, individual trees, etc. 
- [ ] - KF or AG - idea -- bulldozer? blank tile? - as a user I want a way to clear a tile - could this be a special "blank" tile? or maybe I "hold down" on the tile for 1 or 2 seconds and it then explodes?

v2 - AR setup mode (for Q3 and AVP HMD)
- [ ] - ability to pinch, drag and release city hall to set anchor for city grid https://github.com/3DStreet/citybuilderjr/issues/17
- [ ] - instructions "Place your city Hall to begin building." and pinch, drag, release 
- [ ] - city hall placed on pedestal relative to y height of user initiated session
- [ ] - pinching motion artistic spherical embellishment and sfx ([see image](https://github.com/3DStreet/citybuilderjr/assets/470477/a96a2558-51d3-492a-9cb4-ddc757961b8f))
- [ ] - updated landing page "start ar passthru" and "start vr immersive" or alternative option "send to device" 
- [ ] - notify for anchor creation, fail -- add xr mode for notify component similar to "lower third" style quest os bar. note -- what text to use? troika? built-in?
- [ ] - music - kf has some picked out on https://github.com/3DStreet/citybuilderjr/issues/11

v3 - free place props
- [ ] - AG question / research: how to deal with props, vehicles etc free-placed models that do not snap: (a) place within tile as children? (b) or global props relative to origin? or (c) ?
- [ ] - in any case, replacing (or deleting) a tile should delete all of the free-placed models located within this tile region

v3 - category and nicer controls
- [ ] - implement category switcher
- [ ] - define categories
- [ ] - define method to define categories
- [ ] - new control design (category name switch vertically)
- [ ] - instead of whiteboard, billboard
- [ ] - change the scale of cells (larger or smaller models) https://github.com/3DStreet/citybuilderjr/issues/22
- [ ] - increase or decrease the number of cells in the grid https://github.com/3DStreet/citybuilderjr/issues/24

**Comment by Algorush** [comment]
> KF or AG - idea -- bulldozer? blank tile? - as a user I want a way to clear a tile - could this be a special "blank" tile? or maybe I "hold down" on the tile for 1 or 2 seconds and it then explodes?

We can also add new UI element for this
